[package]
name = "qwantzle-search"
version = "0.1.0"
edition = "2021"

[dependencies]
llama_cpp = "0.3.2"
llama_cpp_sys = "0.3.2"
csv = "1.1"
indicatif = "0.17"
clap = { version = "4.5.18", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
machine-info = "1.0.6"

[features]
cuda = ["llama_cpp/cuda", "llama_cpp_sys/cuda"]
